- name: Copy index.php file and move to the server
  hosts: webserver
  tasks:
    - name: Upload index.php file
      copy:
        src: ./config/index.php
        dest: /var/www/html
        mode: 0755
      become: true